feat: Add button (start, restart) #2
In-Self-Improvement/moment-template pull request #8
Opened 2023-06-05 12:34 UTC by borobong2

2023-06-06 01:10 UTC, popocreator requested changes

2023-06-06 01:10 UTC, popocreator commented on src/hooks/useTimer.ts
> +  }, [elapsedTime, isInProcess]);
@borobong2 
elapsedTime 값을 사용하고 있지 않은 것 같은데 들어가 있습니다. updateTimer 함수를 useCallback과 같이 사용하면 더 좋을 것 같습니다.

2023-06-06 01:10 UTC, popocreator commented on src/components/Timer.tsx
> +      )}
@borobong2 인라인 함수를 처음부터 미리 빼 두는 습관을 들이면 더 좋을 것 같습니다.

2023-06-06 10:35 UTC, borobong2 commented on src/hooks/useTimer.ts
> -  }, [elapsedTime, isInProcess]);
미사용하는 elapsedTime 삭제 완료했습니다!

2023-06-06 10:36 UTC, borobong2 commented on src/components/Timer.tsx
> +      )}
@popocreator "시작"이라는 멘트로 인라인 함수를 사용하지 않는 방법이 있을까요?

2023-06-06 14:40 UTC, popocreator approved these changes

2023-06-09 09:28 UTC, borobong2 commented on src/hooks/useTimer.ts
> +  }, [elapsedTime, isInProcess]);
@popocreator 지성님 이 변수(elapsedTime) 가 타이머 진행할때 사용중이라 다시 복원했습니다..

2023-06-09 13:33 UTC, popocreator commented on src/hooks/useTimer.ts
> +  }, [elapsedTime, isInProcess]);
@borobong2 진행중에 쓰이는 변수였군요 ... !! 알겠습니다!

2023-06-16 01:18 UTC, merged